### ISSUE TITLE
Panic when macro is used outside of a function

### ISSUE THREAD

**Issue by SWW13** [rune-rs/rune#426]
`main.rn`
```rune
a!();
```

```
$ rune run main.rn
thread 'main' panicked at 'last id not present', /.cargo/registry/src/github.com-1ecc6299db9ec823/rune-0.12.0/src/shared/items.rs:36:41
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/option.rs:1854:5
   5: rune::indexing::index::file
   6: rune::worker::Worker::run
   7: rune::compile::compile
   8: rune::build::Build::build
   9: rune::loader::load
  10: rune::run_path::{{closure}}
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: std::thread::local::LocalKey<T>::with
  13: tokio::park::thread::CachedParkThread::block_on
  14: tokio::runtime::thread_pool::ThreadPool::block_on
  15: tokio::runtime::Runtime::block_on
  16: rune::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by udoprog** [comment]
As a first step to mitigate I opened #427 without looking too closely into what happened. Some indexing invariant was clearly broken, and given that it's part of the items stack and macro evaluation at the root of the module tree when its empty it seems like something was overlooked.

It might be appropriate for the item stack during to always return a valid id, where the root returns an id corresponding to the root item.
