### ISSUE TITLE
Rune LSP cargo broken with multi-binary crates

### ISSUE THREAD

**Issue by VorpalBlade** [rune-rs/rune#775]
I decided to move from having a separate crate for my LSP to having two binaries in the same crate:

```toml
# ...
[[bin]]
name = "konfigkoll"
path = "src/main.rs"

[[bin]]
name = "konfigkoll-rune"
path = "src/bin/rune.rs"
# ...
```

This doesn't work at all:

```
ERROR [25/07/2024, 11:10:05]: Error: cargo build -p konfigkoll-rune: failed (101)
    at t.Ctx.buildCargoPackage (/home/arvid/.vscode/extensions/udoprog.rune-vscode-0.13.1/dist/extension.js:1:42699)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at t.Ctx.getServer (/home/arvid/.vscode/extensions/udoprog.rune-vscode-0.13.1/dist/extension.js:1:43086)
    at t.Ctx.bootstrap (/home/arvid/.vscode/extensions/udoprog.rune-vscode-0.13.1/dist/extension.js:1:40637)
    at t.Ctx.setupClient (/home/arvid/.vscode/extensions/udoprog.rune-vscode-0.13.1/dist/extension.js:1:40027)
    at t.Ctx.activate (/home/arvid/.vscode/extensions/udoprog.rune-vscode-0.13.1/dist/extension.js:1:39840)
    at /home/arvid/.vscode/extensions/udoprog.rune-vscode-0.13.1/dist/extension.js:1:39450
    at f.h (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:204392) {
  details: 'error: package ID specification `konfigkoll-rune` did not match any packages\n'
}
```

I really don't wish to have to publish an extra crate to crates.io just for the LSP. I would *prefer* if it could even be part of my main binary somehow. But at least let me integrate it into a multi-binary crate.

**Comment by udoprog** [comment]
We now allow for specifying a `Cargo Binary` option when building a local server.

See: https://github.com/rune-rs/rune/releases/tag/editor-0.13.2
